use_frameworks!

target 'LXFProtocolTool_Example' do
    
  pod 'LXFProtocolTool/LXFNibloadable', :path => '../'
  pod 'LXFProtocolTool/Refreshable', :path => '../'
  pod 'LXFProtocolTool/EmptyDataSetable', :path => '../'
  pod 'LXFProtocolTool/AssociatedObjectStore', :path => '../'
  
#  pod 'LXFProtocolTool', :path => '../'

  target 'LXFProtocolTool_Tests' do
    inherit! :search_paths

    
  end
end
